name: homelab

services:

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

    ports:
      - 8080:8080
      - 8989:8989
      - 7878:7878
      - 9696:9696
      - 8096:8096

    volumes:
      - ${HOME}/homelab/gluetun:/gluetun

    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${VPN_COUNTRY}
      - FIREWALL=on
      - TZ=${TZ}

    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    network_mode: service:gluetun

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080

    volumes:
      - ${HOME}/homelab/qbittorrent/config:/config
      - ${HOME}/homelab/downloads:/downloads

    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    network_mode: service:gluetun

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

    volumes:
      - ${HOME}/homelab/prowlarr/config:/config

    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    network_mode: service:gluetun

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

    volumes:
      - ${HOME}/homelab/sonarr/config:/config
      - ${HOME}/homelab/downloads:/downloads
      - ${HOME}/homelab/media/series:/series

    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    network_mode: service:gluetun

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

    volumes:
      - ${HOME}/homelab/radarr/config:/config
      - ${HOME}/homelab/downloads:/downloads
      - ${HOME}/homelab/media/movies:/movies

    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:latest

    ports:
      - 8096:8096

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

    volumes:
      - ${HOME}/homelab/jellyfin/config:/config
      - ${HOME}/homelab/jellyfin/cache:/cache
      - ${HOME}/homelab/media:/media

    restart: unless-stopped
